### ISSUE TITLE
start and end times in Experiment node

### ISSUE THREAD

**Issue by pavel-shliaha** [thermofisherlsms/meth-modifications#1]
In the previous version of software

  <xs:element name="Experiment">
    <xs:complexType>
      <xs:all>
        <xs:element ref="TMSnScan" minOccurs="0" maxOccurs="1" />
        <xs:element ref="FullMSScan" minOccurs="0" maxOccurs="1" />
        <xs:element ref="TargetedInclusionMassListFilter" minOccurs="0" maxOccurs="1" />
        <xs:element name="StartTime" type="xs:double" minOccurs="0" maxOccurs="1" />
        <xs:element name="EndTime" type="xs:double" minOccurs="0" maxOccurs="1" />
      </xs:all>
      <xs:attribute name="ExperimentIndex" type="xs:int" use="required" />
    </xs:complexType>
  </xs:element>

But now its this:

<xs:element name="Experiment">
    <xs:complexType>
      <xs:all>
        <xs:element ref="TMSnScan" minOccurs="0" maxOccurs="1" />
        <xs:element ref="FullMSScan" minOccurs="0" maxOccurs="1" />
        <xs:element ref="TargetedInclusionMassListFilter" minOccurs="0" maxOccurs="1" />
      </xs:all>
      <xs:attribute name="ExperimentIndex" type="xs:int" use="required" />
    </xs:complexType>
  </xs:element>

so experiment start and end are gone. Could you please add this functionality back. Unfortunately all my methods fail without it

**Comment by dbaileychess** [comment]
It is in [2.1](https://github.com/thermofisherlsms/meth-modifications/blob/master/xsds/Calcium/2.1/MethodModifications.xsd#L180). I no longer support 2.0 changes.

**Comment by jacobrayschwartz** [comment]
Hi pavel, I'm one of the new devs at Thermo. Rajesh asked me to look into this. Looks like the fields you're looking for were renamed to StartTimeMin and EndTimeMin for the Experement node in the 2.1 release.

```
  <xs:element name="Experiment">
    <xs:complexType>
      <xs:all>
        <xs:element ref="TMSnScan" minOccurs="0" maxOccurs="1" />
        <xs:element ref="FullMSScan" minOccurs="0" maxOccurs="1" />
        <xs:element ref="TargetedInclusionMassListFilter" minOccurs="0" maxOccurs="1" />
        <xs:element ref="CopyAndAppendScanNode" minOccurs="0" maxOccurs="1" />
        <xs:element ref="ScanNode" minOccurs="0" maxOccurs="1" />
        <xs:element ref="MassListFilter" minOccurs="0" maxOccurs="1" />
        <xs:element name="StartTimeMin" type="xs:double" minOccurs="0" maxOccurs="1" />
        <xs:element name="EndTimeMin" type="xs:double" minOccurs="0" maxOccurs="1" />
      </xs:all>
      <xs:attribute name="ExperimentIndex" type="xs:int" use="required" />
    </xs:complexType>
  </xs:element>
```

**Comment by pavel-shliaha** [comment]
Yes it was. I tested this and it works. Sorry for the confusion!
