### ISSUE TITLE
Scan description to label fragmentation conditions

### ISSUE THREAD

**Issue by pavel-shliaha** [thermofisherlsms/meth-modifications#10]
I have had a very productive talk with @dbaileychess and Shannon at ASMS. We discussed that one of our man problems of the fragmentation optimisation experiments is that it is very complicated to deduce which scans belong to which experiments and conseqeuntly to which fragmentation conditions.

The solution we used in the submitted paper was to add a small mass difference for every condition, e.g. if we target 500 mz, for experiment 1 it will be 500.0001. However, due to some internal instrument settings the mz is not written into the filterString correctly. For example 500.0003 can appear as 500.0002. Derek suggested that this might be a rounding error.

Derek suggested the easiest way to label scans is to implement Scan Description parameter. Is there any news on implementing this?

**Comment by jesse-canterbury** [comment]
There is a scan description parameter now, but I'm not 100% certain whether it's exposed in the xml method modifier.  If you come back to this and try again and it's not there, please submit a new issue with updated information.

Closing this issue as obsolete.
