### ISSUE TITLE
specifying mz in tMS2

### ISSUE THREAD

**Issue by pavel-shliaha** [thermofisherlsms/meth-modifications#11]
We are looking at the XML Schema Definition for 3.1 version and we cannot find a way to change the targeted mz in the tMS2 scans. The problem is in 2.1 MassList node was a child of TMSnScan, however in 3.1 this is no longer the case and it appears that MassList can only be called through MassListFilter. 

But the attributes for  MassListFilter (especially the Above attribute) imply that this is a separate node in methodEditor GUI, which is not compatible with tMS2 at all. 

Any suggestions how we can reach the massList table in tMS2?

**Comment by jacobrayschwartz** [comment]
Hi Pavel, that was an error in editing the XSD for 3.1. The functionality should still be there. I will check on fixing the XSD here

**Comment by pavel-shliaha** [comment]
As suggested by Jacob I checked if the functionality would still work on 3.1. I used the following code (the code works if other modifications are made, e.g. to MS1 resolution). the software produced an error that said that "The elemenst "TMSnScan" has invalid child element, "MassList" ". So it appears that the problem is indeed there

```<?xml version="1.0" encoding="utf-8" ?>
<MethodModifications Version="2" Model="OrbitrapFusionLumos" Family="Calcium" Type="SL">

<Modification Order="1">
<Experiment ExperimentIndex="1">
<TMSnScan>
<MassList>
<MassListRecord>
<MOverZ>1162.0153</MOverZ>
<Z>1</Z>
</MassListRecord>
</MassList>
</TMSnScan>
</Experiment>
</Modification>


</MethodModifications>```

**Comment by jesse-canterbury** [comment]
Closing this issue as obsolete.  If this is still a problem in more recent versions, please feel free to submit a new issue with updated information.
