### ISSUE TITLE
Q Exactive Plus support

### ISSUE THREAD

**Issue by radix-aw** [thermofisherlsms/meth-modifications#16]
Hello. I am interested in modifying the instrument method files for the Q Exactive Plus, but it doesn't seem supported by this project. Is this something that can be provided?

**Comment by MichaelSenko** [comment]
Unfortunately, the format for the Tribrid and QE method files are unrelated.  There are no plans at this time to add this capability to the QE's.

**Comment by radix-aw** [comment]
Understood. Thank you for the prompt reply. My goal is to programmatically populate the inclusion list of an instrument method file. Do you have any recommendations for how I may proceed?

**Comment by caetera** [comment]
> Understood. Thank you for the prompt reply. My goal is to programmatically populate the inclusion list of an instrument method file. Do you have any recommendations for how I may proceed?

Hi @radix-aw, what exactly do you mean by programmatically populate the inclusion list? Do you need to do this on-the-fly? Then you might check the IAPI https://github.com/thermofisherlsms/iapi that seems to support Exactive series as well. Another option might be the targeting app from MQLive, that, was reported to be working on QE Plus https://groups.google.com/forum/#!topic/maxquantlive/9NFv5mzki-I .

**Comment by radix-aw** [comment]
Within the Method Editor there is an "Inclusion List" which lists the expected masses, polarity, etc. of the fragments. I am trying to automate the creation of experiments (sequence files) for the Xcalibur, which necessarily depends on the automatic creation of the instrument method files.

Thanks for the pointer to the IAPI and MQLive. I'll check them out.
