### ISSUE TITLE
GitHub Actions build?

### ISSUE THREAD

**Issue by wfondrie** [thermofisherlsms/meth-modifications#20]
I've added a GitHub Actions workflow to build these projects in my own fork. If you'd be interested adding automated builds, I can put it in as a pull request.

**Comment by jesse-canterbury** [comment]
Thanks a lot for the offer!  We pretty much just use these repos for distribution, hence we are typically uploading just the libraries, and (very) occasional changes to the examples.  Hence we don't have much need for the automated builds.  More to the point though, we're not supposed to be accepting contributions.  But I very much appreciate the offer!
