### ISSUE TITLE
Editing tMS2 experiments on Exploris instruments

### ISSUE THREAD

**Issue by wfondrie** [thermofisherlsms/meth-modifications#21]
Currently, the Exploris XML schema does not allow for editing tMS2 experiments, which we use for PRM and DIA experiments:
https://github.com/thermofisherlsms/meth-modifications/blob/a5cb728ae1040472785f96f82007f02886c150d6/xsds/Exploris/3.3/MethodModifications.xsd#L186-L201

Would it be possible to add the ability to modify the tMS2 mass list, similar to how inclusion and exclusion mass lists are currently allowed? 

It looks like this is already the case for Eclipse instruments, which have a `TMSnScan` experiment element:
 https://github.com/thermofisherlsms/meth-modifications/blob/a5cb728ae1040472785f96f82007f02886c150d6/xsds/Calcium/3.4/MethodModifications.xsd#L241-L257
 
We can accomplish something close to this using an inclusion list (which I can successfully edit programmatically), but it would be nice to modify our tMS2 methods this way. Thanks!

**Comment by RevathiRajagoapalan** [comment]
This is Fixed in the new Build
