### ISSUE TITLE
Exploris 4.2

### ISSUE THREAD

**Issue by meowcat** [thermofisherlsms/meth-modifications#22]
Hi,
before I sink significant time into this: can this work with Exploris method editor 4.2? I have  the Thermo.TNG.MethodXMLInterface.dll and Thermo.TNG.MethodXMLFactory.dll installed, but I am getting "IMethodXML implementation not found" right now (running the Examples with --version modified to 4.2)

**Comment by RevathiRajagoapalan** [comment]
This is Fixed with PR  https://github.com/thermofisherlsms/meth-modifications/pull/24/commits/b56903afe64062cccc7930a122748a4f8ffc6f91
