### ISSUE TITLE
cant find the new features

### ISSUE THREAD

**Issue by pavel-shliaha** [thermofisherlsms/meth-modifications#6]
I got this message from Jacob:

"I’ve just finished updating the repository. You can check out the release/beta-3.1 branch for the latest XmlMethodChanger and the MethodXML.dll files (located in the libs directory)"

I presume that the message refers to github repository. However, if I check the lib directory I getonly 2.0 and 2.1 folders

![versions](https://user-images.githubusercontent.com/1895805/40929003-92458a00-6823-11e8-8694-d7f6a16a4fa1.PNG)

Could you please clarify?

**Comment by aphorton** [comment]
Pavel, the new dll files are in the "release/beta-3.1" branch of this repository, instead of the default "master" branch where you checked.
https://github.com/thermofisherlsms/meth-modifications/tree/release/beta-3.1/lib/3.1

**Comment by pavel-shliaha** [comment]
thanks a lot. I found it. I will check the functionality and report back shortly
